---
- name: "Bootstrap server dependencies"
  hosts: localhost
  become: yes
  tasks:
  - name: "Install Docker dependencies"
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
  - name: "Add Docker GPG key"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: "Add Docker repository"
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu jammy stable
      state: present
  - name: "Install Docker"
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  - name: "Checking docker service status"
    service:
      name: docker
      state: started
      enabled: yes
  - name: "Install system tools"
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    loop:
    - htop
    - ncdu
    - git
    - zsh
    - tree
    - fzf
    - nfs-common

  handlers:
  - name: restart docker
    service:
      name: docker
      state: restarted

