---
- name: Installer les outils .NET et les dépendances nécessaires
  hosts: localhost
  become: yes
  tasks:
    - name: Installer les dépendances nécessaires pour .NET
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gpg-agent
        - software-properties-common
 
    - name: Ajouter le dépôt Microsoft pour .NET
      shell: |
        wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        dpkg -i packages-microsoft-prod.deb
      args:
        creates: /etc/apt/sources.list.d/microsoft-prod.list
 
    - name: Installer le SDK .NET
      apt:
        name: dotnet-sdk-8.0
        state: present
        update_cache: yes
        // a la version